backend:
  name: github
  repo: boiporen-rgb/emran-portfolio-raw # আপনার গিটহাব রিপোজিটরি নাম ঠিক রাখুন
  branch: main

media_folder: "images" # ছবিগুলো এখানে জমা হবে
public_folder: "images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blogs" # ব্লগগুলো এই ফোল্ডারে সেভ হবে
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}