backend:
  name: github
  repo: boiporen-rgb/emran-portfolio-raw # এখানে আপনার সঠিক রিপোজিটরি নাম দিন
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blogs"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}